# Generated by Django 4.2.6 on 2023-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_scope_article_alter_scope_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='article', to='articles.article', verbose_name='Статья'),
        ),
    ]
