# Generated by Django 4.2.6 on 2023-11-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_tag_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='article', through='articles.Scope', to='articles.article', verbose_name='Статья'),
        ),
    ]
